name: Build and Release lpunpack

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Run every day at midnight UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          git \
          wget \
          curl \
          libtool \
          autoconf \
          automake \
          g++ \
          libc6-dev \
          clang \
          pkg-config \
          python3 \
          python3-pip

    - name: Install repo tool
      run: |
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/repo
        chmod a+x ~/repo
        sudo mv ~/repo /usr/local/bin/repo

    - name: Initialize repo for AOSP source
      run: |
        mkdir -p ~/aosp
        cd ~/aosp
        repo init -u https://android.googlesource.com/platform/manifest.git -b master
        repo sync -j4  # Sync only the necessary parts (this is large and may take time)

    - name: Clone lpunpack repository from Google
      run: |
        git clone https://android.googlesource.com/platform/system/extras.git
        cd extras && git checkout main

    - name: Build lpunpack
      run: |
        cd extras/partition_tools
        make lpunpack

    - name: Create archive of lpunpack
      run: |
        tar czvf lpunpack.tar.gz extras/partition_tools/lpunpack

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: lpunpack.tar.gz
        tag_name: latest-${{ github.run_number }}
        name: Latest lpunpack Release ${{ github.run_number }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
